stages:
  load_data: 
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps: 
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog


  prepare_base_model: 
    cmd: python src/stage_02_prepare_base_model.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - config/config.yaml
      - src/utils/models.py
    params:
      - LEARNING_RATE
      - IMAGE_SIZE
    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5

  prepare_callbacks: 
    cmd: python src/stage_03_prepare_callbacks.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_03_prepare_callbacks.py
      - src/utils/all_utils.py
      - config/config.yaml
      - src/utils/callbacks.py
      - params.yaml
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb

  train: 
    cmd: python src/stage_04_train.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_04_train.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - src/utils/data_management.py
      - config/config.yaml
      - src/utils/callbacks.py
      - params.yaml
      - data/cat
      - data/dog
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - AUGMENTATION
      - EPOCHS
    outs:
      - artifacts/model
  
  evaluate: 
    cmd: python src/stage_05_evaluate.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_05_evaluate.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - src/utils/data_management.py
      - config/config.yaml
      - src/utils/callbacks.py
      - params.yaml
      - test_data/cat
      - test_data/dog
      - artifacts/model
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - TEST_BATCH_SIZE
    outs:
      - logs/running_logs.log