AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
TEST_BATCH_SIZE: 1
EPOCHS: 2
CLASSES: 2
BASE_MODEL: VGG16
LEARNING_RATE: 0.001
OPTIMIZER: SGD
COLOR_MODE: rgb
CLASS_MODE: None
SHUFFLE: False