
artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECKPOINT_DIR: checkpoint
  BASE_LOG_DIR: base_model_dir
  TENSORBORD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data
  TEST_DIR: test_data

source_download_dirs:
  - ../outside_data/dog
  - ../outside_data/cat
  - ../outside_data/testing/cat
  - ../outside_data/testing/dog

local_data_dirs:
  - data/dog
  - data/cat
  - test_data/cat
  - test_data/dog

