
artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASED_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_ BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECKPOINT_DIR: checkpoint
  BASE_LOG_DIR: base_model_dir
  TENSORBORD_ROOT_LOG_DIR: tesnsotboard_log_dir
  CALLBACKS_DIR: callbacks


source_download_dir:
  - ../outside_data/dog
  - ../outside_data/cat

local_path_dir:
  - data/dog
  - data/cat